---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

words: boat,book,vote,seat,backpack,partition,groundhog


server:
  port: ${PORT:${SERVER_PORT:0}}
