---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
  port: ${PORT:${SERVER_PORT:0}}

---
spring:
  profiles: subject
  application:
    name: subject

---
spring:
  profiles: verb
  application:
    name: verb

---
spring:
  profiles: adjective
  application:
    name: adjective

---
spring:
  profiles: noun
  application:
    name: noun